# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73d5e6c556e4d66f808dd84bce3cf0ea202d0998f2b720a7bc0d90e025a0b08b9ea91df78fe75d44cfe0186902129bbac481bd73e6ee49aa9dc3e0e2191c2d6a

test:
  secret_key_base: 47fec579ebd7746c24bc2f652f0c0a523840ca34740790ac8400c9bdaca4bb4d117fae1c37b5f44aaf5c5a245726f9bc0646bad3df2dce7ade18b1a061fe670a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
